version: '3.6'
services:
  postgres:
    image: postgres:12
    ports:
    - "5432:5432"
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    - ./postgres-setup:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: pwd
